#ifndef DNG_PUBLIC_DEFINE
#define DNG_PUBLIC_DEFINE
#define DNG_VERSION "1.0.0 Beta"
#define COMMAND_MAXLENGTH 256
#define PATH_MAXLENGTH 1024
#define BUFFER_LENGTH 1024
#define TEMP_BUFFER_LENGTH BUFFER_LENGTH
#define DNG_EXTENSION_INSTALL_DIRECTORY "installed"
#define DNG_EXTENSION_RESULT_DIRECTORY "result"
#define DNG_EXTENSION_HELP_FILE "help.txt"
#define DNG_EXTENSION_OUTPUT_FILE_SUFFIX_NAME "txt"
#define DNG_EXTENSION_RECORD_FILE "install.note"
#define DNG_EXTENSION_CLOSE_FILE "remove.lock"
#endif
